### ISSUE TITLE
Unable to expand HAR archive log dir

### ISSUE THREAD

**Issue by asdf1234-deleted** [rkanter/ALFExploder#1]
Output:

```
[mtdeguzis@HOST: alf-exploder]$ sudo -u hdfs hadoop fs -ls har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775

Found 2 items
-rw-r--r--   3 cdis_hdp_prod hadoop      12221 2018-07-19 23:10 har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775/HOST.geisinger.edu_45454
-rw-r--r--   3 cdis_hdp_prod hadoop      16082 2018-07-19 23:10 har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775/HOST.geisinger.edu_45454

[mtdeguzis@HOST: alf-exploder]$ ./run.sh --applogdir /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775 -outputdir ~/logtest/
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.io.FileNotFoundException: File /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775 does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:431)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1517)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1557)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1714)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1713)
        at org.apache.hadoop.fs.ChecksumFileSystem.listLocatedStatus(ChecksumFileSystem.java:689)
        at com.github.rkanter.alfexploder.ALFExploder.explode(ALFExploder.java:82)
        at com.github.rkanter.alfexploder.ALFExploder.run(ALFExploder.java:69)
        at com.github.rkanter.alfexploder.ALFExploder.main(ALFExploder.java:36)

[mtdeguzis@HOST: alf-exploder]$ ./run.sh --applogdir har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775 -outputdir ~/logtest/
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.io.IOException: Invalid path for the Har Filesystem. No index file in har:/app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har
        at org.apache.hadoop.fs.HarFileSystem.initialize(HarFileSystem.java:148)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.github.rkanter.alfexploder.ALFExploder.explode(ALFExploder.java:77)
        at com.github.rkanter.alfexploder.ALFExploder.run(ALFExploder.java:69)
        at com.github.rkanter.alfexploder.ALFExploder.main(ALFExploder.java:36)
```

I didn't see an example for HAR archive usage, but used the same format as 'hadoop fs' would.

**Comment by asdf1234-deleted** [comment]
Checked usage, such as 3 slashes vs 2. Removed extra dash on applogdir arg. Tried quoting input path.

```
bash -x run.sh -applogdir "har://app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775" -outputdir ~/logtest/
```

>How to Look Up Files in Archives
The archive exposes itself as a file system layer. So all the fs shell commands in the archives work but with a different URI. Also, note that archives are immutable. So, rename’s, deletes and creates return an error. URI for Hadoop Archives is
>
>har://scheme-hostname:port/archivepath/fileinarchive
>
>If no scheme is provided it assumes the underlying filesystem. In that case the URI would look like
>
>har:///archivepath/fileinarchive

**Comment by rkanter** [comment]
I can't double check at the moment, but I'm pretty sure that you should simply point the program at the har "file" (directory) itself, instead of actually using it.  So no "har:///" and you would end the path at the ".har" without the "application_1531680494766_96775" at the end.

Something like:
`./run.sh --applogdir /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har -outputdir ~/logtest/`
Does this work?

The program will figure out how to deal with the HAR file.  More specifically, https://github.com/rkanter/ALFExploder/blob/master/src/main/java/com/github/rkanter/alfexploder/ALFExploder.java#L87 it checks if it's a HAR file by looking at the end of the filename (".har") and https://github.com/rkanter/ALFExploder/blob/master/src/main/java/com/github/rkanter/alfexploder/ALFExploder.java#L105 where it will prepend the "har:///" system.

If that's the case, I'll update the README with more complicated usage examples (HAR file, file on HDFS, etc) probably sometime next week.

**Comment by asdf1234-deleted** [comment]
Yea, I did try that with no success after reviewing the code:

```
$ alf-exploder-upstream]$ ./run.sh -applogdir /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har -outputdir ~/logtest/
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.io.FileNotFoundException: File /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har does not exist
        at org.apache.hadoop.fs.RawLocalFileSystem.listStatus(RawLocalFileSystem.java:431)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1517)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1557)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1714)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1713)
        at org.apache.hadoop.fs.ChecksumFileSystem.listLocatedStatus(ChecksumFileSystem.java:689)
        at com.github.rkanter.alfexploder.ALFExploder.explode(ALFExploder.java:82)
        at com.github.rkanter.alfexploder.ALFExploder.run(ALFExploder.java:69)
        at com.github.rkanter.alfexploder.ALFExploder.main(ALFExploder.java:36)

$ sudo -u hdfs hadoop fs -ls har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775

Found 2 items
-rw-r--r--   3 user hadoop      12221 2018-07-19 23:10 har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775/host.domain.com,_45454
-rw-r--r--   3 user hadoop      16082 2018-07-19 23:10 har:///app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har/application_1531680494766_96775/host.domain.com,_45454
```

**Comment by rkanter** [comment]
@mtdeguzis It turns out that there were a few things going on here:

1. Regardless of whether the logs are in the "plain" format or HAR format, you always should point the tool at the parent directory.  Pointing it at a HAR file or inside the HAR file is not correct.
2. In testing this, I discovered that the tool was missing the HDFS jars needed for connecting to HDFS.  I've fixed that in ca5b3e2d38ff87f5935a0ad11d0d0b57c43b488f.
3. I also discovered that the tool wasn't properly forming the path to the HAR file when on a remote filesystem (like HDFS).  That's fixed in 4508ff7864ca5e01d5cb263a99ec4f758412b4bc.  

I've also updated the README with more details on what the input should look like, as well as some more examples.

It is possible to directly reference a HAR file on the local or remote filesystems, but I'd recommend against that because it's more complicated.  If you do need to do this, you can see how in Examples 3 and 4 in the README.

**Comment by asdf1234-deleted** [comment]
Ok So this won't work?
{code}
./run.sh -applogdir har:///app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.3.har/application_1532350489393_21664 -outputdir ~/applogtest
{code}

Our HAR archives have multiple applog dirs in in it (otherwise a 5-part HAR bundle would be massive). We make HAR archives to avoid the small files problem. If the utility let you specify the app log id, maybe it could expand a sub dir?

>Regardless of whether the logs are in the "plain" format or HAR format, you always should point the tool at the parent directory. Pointing it at a HAR file or inside the HAR file is not correct.

I am not sure how this relates to examples 1 and 2?
Here is the "parent dir" of our har archives:

```
$ sudo -u hdfs hadoop fs -ls /app-logs/cdis_hdp_prod/har-archives/
Found 7 items
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-08-19 02:45 /app-logs/cdis_hdp_prod/har-archives/2018-08-19-har-archive.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-10 14:17 /app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.0.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-10 15:06 /app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.1.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-10 15:40 /app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.2.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-10 16:15 /app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.3.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-10 16:37 /app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.4.har
drwxr-xr-x   - cdis_hdp_prod hadoop          0 2018-09-18 10:14 /app-logs/cdis_hdp_prod/har-archives/2018-09-18-har-archive.har
[mtdeguzis@GDCHDPMN04PRLX: alf-exploder-upstream]$
```


```
$ ./run.sh -applogdir hdfs://app-logs/cdis_hdp_prod/har-archives -outputdir ~/applogtest
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.github.rkanter.alfexploder.ALFExploder.explode(ALFExploder.java:77)
        at com.github.rkanter.alfexploder.ALFExploder.run(ALFExploder.java:69)
        at com.github.rkanter.alfexploder.ALFExploder.main(ALFExploder.java:36)
```

With HDFS host/port:
```
[mtdeguzis@GDCHDPMN04PRLX: alf-exploder-upstream]$ ./run.sh -applogdir hdfs://HOST:50070/app-logs/cdis_hdp_prod/har-archives -outputdir ~/applogtest
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.github.rkanter.alfexploder.ALFExploder.explode(ALFExploder.java:77)
        at com.github.rkanter.alfexploder.ALFExploder.run(ALFExploder.java:69)
        at com.github.rkanter.alfexploder.ALFExploder.main(ALFExploder.java:36)
```

**Comment by rkanter** [comment]
How are you generating the HAR files?  Is it something custom that you're doing?  Or are you using the [`mapred archive-logs` command](https://hadoop.apache.org/docs/current/hadoop-archive-logs/HadoopArchiveLogs.html)?  

This tool was written to work with the `mapred archive-logs` command, which generates HAR files in a specific layout, with only one Application's logs per HAR file.  As explained in the updated README, for a HAR file, this layout should look like `/path/to/somewhere/<application_id>/<application_id>.har`.  The instructions about the parent dir assume you're using the standard layout.  From what you've posted, it sounds like you must be using the `mapred archive` command and doing something custom.  

In that case, you'll need to do something similar to examples 3 and 4, where you specify the HAR filesystem itself.  
If this is the local disk, I believe this (the first command you suggested in your latest comment) should work, but I can't test it:
`./run.sh -applogdir har:///app-logs/cdis_hdp_prod/har-archives/2018-09-10-har-archive.3.har/application_1532350489393_21664 -outputdir ~/applogtest`
(I'm assuming that there's one or more files under this `application_1532350489393_21664` directory in the HAR file with the aggregated logs for application_1532350489393_21664, right?)

Did you make sure to update the repo and run `build.sh` again?
(I'm guessing not because I fixed the " No FileSystem for scheme: hdfs" error the other day).

**Comment by asdf1234-deleted** [comment]
Bah, sorry, I didn't recompile, feel silly now. Let me do that soon and get back to you. Thank you for working with me on this.
